# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 621c05249f101e47cc5c8e8f51ac04674fce94bc6ef8784c3dc95029366995ddc900752a0fadce63d1095d66fe1a858ca4aa8fc4720c7d0c090507ef41550976

test:
  secret_key_base: 8430977add09bd6617f4e4f2821d08465ee1ffc43d3d417bc82af8fabd2be7bf008c94bf4167fb7ed76893539fa7576a0714cd15741f70b5c95fac8eb2575ea8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
